version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: userorderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_DB: mydb
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: pass
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   api:
#     build: .
#     ports:
#       - "8080:8080"
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_NAME=mydb
#       - DB_USER=user
#       - DB_PASSWORD=pass
#       - JWT_SECRET=secret
#       - PORT=8080
#     depends_on:
#       - db

# volumes:
#   pgdata:
